bi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: bi
    username: root
    password: root
  redis:
    database: 1
    host: 192.168.232.135
    password: 1523025069
    port: 6379
    timeout: 5000